name: "web_app"
port: 8081
mode: "dev"
start_time: "2022-01-25"
machine_id: 1

log:
  level: "debug"
  filename: "web_app.log"
  max_size: 200
  max_age: 30
  max_backups: 7

mysql:
  host: "127.0.0.1"
  port: 3306
  user: "root"
  password: "123456"
  dbname: temp
  max_idle: 20
  max_connect_count: 10

redis:
  host: "127.0.0.1"
  port: 6379
  password: 123456
  db: 1
  pool_max_size: 20